In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
columns=[
    'place',
    'administrative_unit',
    'population'
]

In [3]:
data=pd.read_csv('../data/population.csv', names=columns)

In [4]:
data.head()

                           place administrative_unit  population
0     BBMP Municipal Corporation           Karnataka     8443675
1  Anekal Town Municipal Council           Karnataka       44260
2          Hebbagodi Census Town           Karnataka       34827
3           Attibele Census Town           Karnataka       20532
4             Jigani Census Town           Karnataka       17036

In [5]:
data

                             place administrative_unit  population
0       BBMP Municipal Corporation           Karnataka     8443675
1    Anekal Town Municipal Council           Karnataka       44260
2            Hebbagodi Census Town           Karnataka       34827
3             Attibele Census Town           Karnataka       20532
4               Jigani Census Town           Karnataka       17036
5          Bommasandra Census Town           Karnataka       15254
6          Dommasandra Census Town           Karnataka       12610
7            Sarjapura Census Town           Karnataka       11807
8       Maragondahalli Census Town           Karnataka        8824
9                      A Medihalli              Anekal         451
10               Adigarakallahalli              Anekal        2915
11                 Adigondanahalli              Anekal        1354
12                            Adur              Anekal         717
13             Agasa Thimmanahalli              Anekal          22
14                 Ali Bommasandra              Anekal         700
15                 Amani Doddakere              Anekal          32
16                        Andapura              Anekal        1769
17                          Anekal              Anekal        1575
18                  Aravantigepura              Anekal         247
19                        Arehalli              Anekal         851
20                          Arenur              Anekal         630
21                  Avadadenahalli              Anekal         680
22                      Avalahalli              Anekal         551
23                     B.Hosahalli              Anekal        1205
24                    Bagganadoddi              Anekal         386
25                 Balagaranahalli              Anekal        5447
26                          Ballur              Anekal        4572
27                       Banahalli              Anekal         475
28                       Banahalli              Anekal        5819
29                       Bandapura              Anekal         853
..                             ...                 ...         ...
551                      Jothipura      Bangalore East        1227
552               Kachamaranahalli      Bangalore East        1056
553                  Kada Agrahara      Bangalore East         835
554            Kadusonnappanahalli      Bangalore East        2498
555                    Kammasandra      Bangalore East         315
556                   Kannamangala      Bangalore East        4381
557                    Katamnallur      Bangalore East        1954
558                Kattugollahalli      Bangalore East         966
559             Khaji Sonnenahalli      Bangalore East        1812
560                     Kithiganur      Bangalore East        3920
561                        Kodathi      Bangalore East        2911
562                    Kodigehalli      Bangalore East         152
563                   Konadasapura      Bangalore East        4170
564             Kurudusonnenahalli      Bangalore East        1074
565                  Lagumenahalli      Bangalore East         306
566                         Mandur      Bangalore East        2295
567               Maragondanahalli      Bangalore East        3014
568                 Mittaganahalli      Bangalore East        1010
569                        Mulluru      Bangalore East        3416
570            Nadagowdagollahalli      Bangalore East         681
571                   Nimbekaipura      Bangalore East         898
572                 Raghuvanahalli      Bangalore East         142
573                        Rampura      Bangalore East        2680
574                     Seegehalli      Bangalore East        3858
575                  Shringaripura      Bangalore East          15
576                      Sulikunte      Bangalore East        2295
577                 Thirumenahalli      Bangalore East         555
578                       Valepura      Bangalore East        1213
579                   Veerenahalli      Bangalore East        2182
580                 Yerappanahalli      Bangalore East        1418

[581 rows x 3 columns]